# Generated by Django 3.0.5 on 2020-04-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAHADEV', '0003_geeksmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geeksmodel',
            name='Name',
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='event_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
