# Generated by Django 3.0.5 on 2020-04-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAHADEV', '0004_auto_20200430_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='event_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
