# Generated by Django 3.0.5 on 2020-04-29 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MAHADEV', '0006_auto_20200430_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geeksmodel',
            name='event_name',
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='Event_name',
            field=models.CharField(default=datetime.datetime(2020, 4, 29, 19, 34, 43, 759041, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
