# Generated by Django 3.0.5 on 2020-04-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAHADEV', '0008_auto_20200430_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='EEvent_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
