# Generated by Django 3.0.5 on 2020-04-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAHADEV', '0009_auto_20200430_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geeksmodel',
            name='EEvent_name',
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='event',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
